config/routes.rb
Dataxu::Application.routes.draw do
  resources :initiaries
  resources :currencies
  resources :countries

  match "/currencies/:id/collect" => "countries#collect"
  match "update" => "application#update_country_data"
  match "remaining_index" => "currencies#remaining_index"
  match "log_in" => "application#log_in"
  match "log_out" => "application#log_out"

  root :to => "home#index"

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :monetizations
  has_many :currencies, :through => :monetizations

  has_many :initiarizations
  has_many :initiaries, :through => :initiarizations
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :monetizations
  has_many :countries, :through => :monetizations
end

app/models/initiarization.rb
class Initiarization < ActiveRecord::Base
  belongs_to :country
  belongs_to :initiary
end

app/models/initiary.rb
class Initiary < ActiveRecord::Base
  has_many :initiarizations
  has_many :countries, :through => :initiarizations
end

app/models/monetization.rb
class Monetization < ActiveRecord::Base
  belongs_to :country
  belongs_to :currency
end

app/controllers/application_controller.rb
require 'savon'
require 'hpricot'

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate, :only => [:log_in]

  def update_country_data
    Thread.new {
      begin
        # setup Savon client for SOAP requests
        client = Savon::Client.new "http://www.webservicex.net/country.asmx?WSDL"

        # test if "webservicex.net" server is up and running
        actions = client.wsdl.soap_actions

        raise "SOAP server is down" if actions.nil? or actions.length <= 0

        resp = client.request :get_currencies

        raise "No response for currencies" if resp.nil?

        doc = Hpricot resp.to_hash[:get_currencies_response][:get_currencies_result]

        a = doc.search "table"

        a.each do |e|
          country = Country.new :name => (e.at "name").inner_html
          country.save

          currency = Currency.new :name => (e.at "currency").inner_html
          currency.save

          monetization = Monetization.new :country_id => country.id, :currency_id => currency.id
          monetization.save
        end
      end
    }
    
    flash[:notice] = "Updating process started..."
    
    redirect_to root_path
  end
  
  def log_out
    session[:uid] = nil
    redirect_to root_path
  end

  def log_in
    if authenticate
      flash[:error] = "Error logging in"
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      r = (username == "moo" && password == "foo")
      session[:uid] = r
      return r
    end
  end

  def encode(phrase)
    Digest::SHA2.hexdigest(Digest::MD5.hexdigest(phrase))
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :authenticate, :only => [ :collect ]
  
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
  end

  def collect
    (Monetization.where :country_id => params[:id]).each do |m|
      m.update_attribute :collected => true
    end
    
    redirect_to :back
  end

=begin
  # GET /countries/new
  # GET /countries/new.xml
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.xml
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to(@country, :notice => 'Country was successfully created.') }
        format.xml  { render :xml => @country, :status => :created, :location => @country }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @country.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.xml
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to(@country, :notice => 'Country was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @country.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.xml
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to(countries_url) }
      format.xml  { head :ok }
    end
  end
=end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_filter :authenticate, :only => [ :collect ]
  
  def index
    @currencies = Currency.all
  end

  def remaining_index
    @currencies = ((Monetization.where :collected => false).collect { |x| x.currency }).uniq
  end

  def show
    @currency = Currency.find(params[:id])
    @visited = (Monetization.where :collected => true, :currency_id => @currency.id).collect { |x| x.country }
  end

  def collect
    unless params[:country_id].nil?
      (Monetization.where :currency_id => params[:currency_id], :country_id => params[:country_id]).each do |m|
        m.update_attribute :collected => true
      end
    else
      (Monetization.where :currency_id => params[:currency_id]).each do |m|
        m.update_attribute :collected => true
      end
    end

    redirect_to :back
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def log_in
  end

  def log_out
  end

end

app/controllers/initiaries_controller.rb
class InitiariesController < ApplicationController
  # GET /initiaries
  # GET /initiaries.xml
  def index
    @initiaries = Initiary.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @initiaries }
    end
  end

  # GET /initiaries/1
  # GET /initiaries/1.xml
  def show
    @initiary = Initiary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @initiary }
    end
  end

  # GET /initiaries/new
  # GET /initiaries/new.xml
  def new
    @initiary = Initiary.new
    @countries = Country.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @initiary }
    end
  end

  # GET /initiaries/1/edit
  def edit
    @initiary = Initiary.find(params[:id])
  end

  # POST /initiaries
  # POST /initiaries.xml
  def create
    #raise "breakpoint"
    
    @initiary = Initiary.new(params[:initiary])
    @initiary.save

    params[:country].each do |c|
      country = Country.find c
      
      r = Initiarization.new :country_id => country.id, :initiary_id => @initiary.id
      r.save

      monetizations = Monetization.where :country_id => country.id

      monetizations.each do |m|
        m.update_attribute :collected, true
      end
    end

    respond_to do |format|
      if @initiary.save
        format.html { redirect_to(@initiary, :notice => 'Initiary was successfully created.') }
        format.xml  { render :xml => @initiary, :status => :created, :location => @initiary }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @initiary.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /initiaries/1
  # PUT /initiaries/1.xml
  def update
    @initiary = Initiary.find(params[:id])

    respond_to do |format|
      if @initiary.update_attributes(params[:initiary])
        format.html { redirect_to(@initiary, :notice => 'Initiary was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @initiary.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /initiaries/1
  # DELETE /initiaries/1.xml
  def destroy
    @initiary = Initiary.find(params[:id])
    @initiary.destroy

    respond_to do |format|
      format.html { redirect_to(initiaries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth?
    !(session[:uid].nil?)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/initiaries_helper.rb
module InitiariesHelper
end

app/views/countries/index.html.erb
<h1>Avaliable countries</h1>

<% @countries.each do |country| %>
  <div id="#{country.name}">
    <%= link_to country.name, country %>
  </div>
<% end %>

<br />

<% if @countries.length <= 0 %>
  You've got no currencies nor countries data.
  We recommend you to <%= link_to "update country and currency lists", :controller => "application", :action => "update_country_data" %> as soon as it's possible
<% end %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @country.name %>
</p>

<p>
  <b>Currencies:</b><br/>
  <br />
  <% @country.currencies.each do |c| %>
    <%= link_to c.name, currency_path(c) %>&nbsp;
    
    <% if auth? %>
      <%= link_to "Collect everything", :controller => :countries, :action => :collect, :id => c.id %>
    <% end %>
  <% end %>
</p>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Collected</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.name %></td>
    <td><%= currency.collected %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/remaining_index.html.erb
<h1>Listing currencies with countries unvisited</h1>

<% @currencies.each do |currency| %>
  <% unless currency.name.empty? %>
    <% visited = (currency.monetizations.where :collected => true).count %>
    <% remaining = (currency.monetizations.where :collected => false).count %>
    <% str = "Visited #{ visited } countries out of #{ remaining }" %>

    <%= link_to currency.name, currency %>&nbsp;<%= str %>&nbsp;

    <% if auth? %>
      <%= link_to "Collect everything", :controller => :currencies, :action => :collect, :currency_id => currency.id %>
    <% end %>

    <br/>
  <% end %>
<% end %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>

<p>
  <b>Avaliable at:</b><br/>
  <br/>
  <% @currency.countries.each do |c| %>
    <%= link_to c.name, c %>
  <% end %>
</p>

<% unless @visited.empty? %>
  <p>
    <b>Countries, visited for <%= @currency.name %>:</b>
    <% @visited.each do |c| %>
      <%= link_to c.name, c %>
    <% end %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>dataxu test project</h1>
<br />
<% unless flash[:errors].nil? || flash[:errors].blank? %>
  <% flash[:errors].each do |msg| %>
    <%= msg %><br />
  <% end %>
  <br />
<% end %>
  
<%= link_to "Avaliable countries", countries_path %><br />
<%= link_to "Avaliable currencies", currencies_path %><br />
<%= link_to "Avaliable currencies with countries unvisited", :controller => :currencies, :action => :remaining_index %><br />
<%= link_to "Initiaries", initiaries_path %><br />

app/views/home/log_in.html.erb
<h1>Loggin' in</h1>
<br />
<%= form_tag "application#log_in", :method => "post" do %>
  <%= label_tag :username, "Your name:" %>
  <%= text_field_tag :username %>
  <%= label_tag :password, "Password:" %>
  <%= password_field_tag :password %>
  <%= submit_tag "Log me in!" %>
<% end %>

app/views/home/log_out.html.erb
<h1>Home#log_out</h1>
<p>Find me in app/views/home/log_out.html.erb</p>

app/views/initiaries/_form.html.erb
<%= form_for(@initiary) do |f| %>
  <% if @initiary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiary.errors.count, "error") %> prohibited this initiary from being saved:</h2>

      <ul>
        <% @initiary.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    Countries visited:<br />
    <% @countries.each do |c| %>
      <% name = c.name.gsub(/\s/, '_') %>
      <%= check_box_tag "country[]", c.id %>
      <%= label_tag "country[#{c.id}]", c.name %>
      <br />
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/initiaries/edit.html.erb
<h1>Editing initiary</h1>

<%= render 'form' %>

<%= link_to 'Show', @initiary %> |
<%= link_to 'Back', initiaries_path %>

app/views/initiaries/index.html.erb
<h1>Listing initiaries</h1>

<% @initiaries.each do |initiary| %>
  <%= link_to initiary.name, initiary %>
  <% if auth? %>
    <br />
    [<%= link_to 'Edit', edit_initiary_path(initiary) %>]&nbsp;
    [<%= link_to 'Destroy', initiary, :confirm => 'Are you sure?', :method => :delete %>]&nbsp;
  <% end %>
  <br />
<% end %>

<br />

<% if auth? %>
  <%= link_to 'New Initiary', new_initiary_path %>
<% end %>

app/views/initiaries/new.html.erb
<h1>New initiary</h1>

<%= render 'form' %>

<%= link_to 'Back', initiaries_path %>

app/views/initiaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @initiary.name %>
</p>

<p>
  <b>Description:</b>
  <%= @initiary.description %>
</p>

<p>
  <b>Countries included:</b><br />
  <% @initiary.countries.each do |c| %>
    <%= link_to c.name, c %><br />
  <% end %>
</p>

<% if auth? %>
  <%= link_to 'Edit', edit_initiary_path(@initiary) %> |
  <%= link_to 'Back', initiaries_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dataxu</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>

    <% if auth? %>
      <%= link_to "Log out", :controller => :application, :action => :log_out %>
    <% else %>
      <%= link_to "Log in", :controller => :application, :action => :log_in %>
    <% end %>

    <%= yield %>

  </body>
</html>